### ISSUE TITLE
Does not work on 1.1DP

### ISSUE THREAD

**Issue by Spechen** [ItsMos/flatbed-ragemp#2]
Hello,

I would like to take your script to a RP Server that I'm developping, but after the end of the rope segment, the car throwing the flatbed.
I made a video to understand the issue : https://youtu.be/jmnz396Q5m0

I think the issue comes from the rope that's not deleted, I think

Such a great work, hope you found a correction

**Comment by JJiGolem** [comment]
Fixed https://github.com/ItsMos/flatbed-ragemp/pull/4
