### ISSUE TITLE
Hi brother

### ISSUE THREAD

**Issue by Muskito667** [ItsMos/flatbed-ragemp#3]
How much u want to make it work without bugs on 1.1 ?? I have the bug the flatbed start to fly random and after go undermap

**Comment by ItsMos** [comment]
Now you can change this line and make the collision to false.
https://github.com/ItsMos/flatbed-ragemp/blob/fc446c286da501da6194e16262d6bb6c043038fc/client_packages/flatbed.js#L408

**Comment by Muskito667** [comment]
Doesn't work, i tried to change single one to false for all, and i tried to all false but after I press X to get the car up, the flatbed start to fly random

**Comment by JJiGolem** [comment]
Fixed https://github.com/ItsMos/flatbed-ragemp/pull/4
